databases:
  - name: HandMovies_DB
    databaseName: handmovies_db_lmwd
    user: HandMovies
    region: singapore

services:
  - type: web
    name: HandMovies
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: HandMovies_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false