default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: <%= ENV['POSTGRES_HOST'] %> 下記に変更
  host: dpg-cggi2064daddcg438grg-a
  #追加
  port: 5432
  database: handmovies_db_lmwd
  #database: <%= ENV['POSTGRES_DB'] %>
  username: shumpei0902
  password: AsanoShumpei0902

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

