default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 4 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  username: postgres
  password: AsanoShumpei0902

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

