default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['POSTGRES_HOST'] %>
  database: handmovies_db
  #database: <%= ENV['POSTGRES_DB'] %>
  username: shumpei0902
  password: AsanoShumpei0902

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
    #追加文
    url: <%= ENV['DATABASE_URL'] %>

