default: &default
  adapter: postgresql
  #encoding: unicode
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #host: <%= ENV['POSTGRES_HOST'] %> 下記に変更
  host: dpg-cggi2064daddcg438grg-a
  #追加
  port: 5432
  #database: <%= ENV['POSTGRES_DB'] %> 下記に変更
  database: handmovies_db_lmwd
  username: shumpei0902
  password: Lc6R7GlpHftlIq58dqTu2GIPPxHnEmdy

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

